# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Template
metadata:
  name: activemq
  annotations:
    iconClass: icon-activemq
    description: Openshift template for ActiveMQ service
    openshift.io/provider-display-name: EDP
    openshift.io/support-url: https://www.epam.com
    tags: edp
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${SERVICE_NAME}-data"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_CAPACITY}
    storageClassName: ${STORAGE_CLASS}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: "Route for ${SERVICE_NAME} service."
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${SERVICE_NAME}
    port:
      targetPort: ui
- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    ports:
    - name: jms
      port: 61616
    - name: ui
      port: 8161
    - name: amqp
      port: 5672
    - name: stomp
      port: 61613
    - name: mqtt
      port: 1883
    - name: ws
      port: 61614
    selector:
      app: ${SERVICE_NAME}
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      type: Rolling
      rollingParams:
        failurePolicy: Abort
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
      spec:
        serviceAccountName: ${SERVICE_NAME}
        containers:
        - name: ${SERVICE_NAME}
          image: "${SERVICE_IMAGE}:${SERVICE_VERSION}"
          imagePullPolicy: Always
          ports:
            - name: jms
              containerPort: 61616
            - name: ui
              containerPort: 8161
            - name: amqp
              containerPort: 5672
            - name: stomp
              containerPort: 61613
            - name: mqtt
              containerPort: 1883
            - name: ws
              containerPort: 61614
          env:
            - name: ACTIVEMQ_NODENAME
              value: ${SERVICE_NAME}
            - name: ACTIVEMQ_ADMIN_LOGIN
              valueFrom:
                secretKeyRef:
                    name: ${SERVICE_NAME}
                    key: activemq.username
            - name: ACTIVEMQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: ${SERVICE_NAME}
                    key: activemq.password
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
          volumeMounts:
            - mountPath: /opt/activemq/data
              name: "${SERVICE_NAME}-data"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        volumes:
        - name: "${SERVICE_NAME}-data"
          persistentVolumeClaim:
            claimName: "${SERVICE_NAME}-data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        initContainers:
          - command:
            - sh
            - '-c'
            - >-
              chown activemq:activemq /mnt/data && cp -a /opt/activemq/data/* /mnt/data/
            image: "${SERVICE_IMAGE}:${SERVICE_VERSION}"
            imagePullPolicy: IfNotPresent
            name: init-activemq
            resources: {}
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /mnt/data
                name: "${SERVICE_NAME}-data"
    triggers:
      - type: ConfigChange
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${SERVICE_NAME}
  stringData:
    activemq.username: ${USERNAME}
    activemq.password: ${PASSWORD}
parameters:
- displayName: Service name
  name: SERVICE_NAME
  required: true
  value: "activemq"
- displayName: Service version
  name: SERVICE_VERSION
  required: true
  value: "5.15.6"
- displayName: Service image
  name: SERVICE_IMAGE
  required: true
  value: "epamedp/activemq"
- displayName: Activemq user
  name: USERNAME
  required: true
  value: "admin"
- displayName: Activemq password
  name: PASSWORD
  required: true
  value: "secret-active"
- displayName: Activemq storage class
  name: STORAGE_CLASS
  required: true
  value: "gp2"
- displayName: Activemq storage capacity
  name: STORAGE_CAPACITY
  required: true
  value: "1Gi"