# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Template
metadata:
  name: rabbitmq
  annotations:
    iconClass: icon-rabbitmq
    description: Openshift template for RabbitMQ service
    openshift.io/provider-display-name: EDP
    openshift.io/support-url: https://www.epam.com
    tags: edp
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${SERVICE_NAME}-data"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "{{ item_map.storage.capacity }}"
    storageClassName: "{{ item_map.storage.class }}"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: "Route for ${SERVICE_NAME} service."
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${SERVICE_NAME}
    port:
      targetPort: management
- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    ports:
    - name: listener
      port: 5672
    - name: management
      port: 15672
    selector:
      app: ${SERVICE_NAME}
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      type: Rolling
      rollingParams:
        failurePolicy: Abort
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
      spec:
        serviceAccountName: ${SERVICE_NAME}
        containers:
        - name: ${SERVICE_NAME}
          image: "${SERVICE_IMAGE}:${SERVICE_VERSION}"
          imagePullPolicy: Always
          ports:
            - name: listener
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                    name: "rabbitmq-secret"
                    key: rabbitmq.username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                    name: "rabbitmq-secret"
                    key: rabbitmq.password
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: "${SERVICE_NAME}-data"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        volumes:
        - name: "${SERVICE_NAME}-data"
          persistentVolumeClaim:
            claimName: "${SERVICE_NAME}-data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
- kind: Secret
  apiVersion: v1
  metadata:
    name: "rabbitmq-secret"
  stringData:
    rabbitmq.username: ${USERNAME}
    rabbitmq.password: ${PASSWORD}
parameters:
- displayName: Service name
  name: SERVICE_NAME
  required: true
  value: "rabbitmq"
- displayName: Service version
  name: SERVICE_VERSION
  required: true
  value: "3.7.5"
- displayName: Service image
  name: SERVICE_IMAGE
  required: true
  value: "rabbitmq"
- displayName: Rabbitmq user
  name: USERNAME
  required: true
  value: "admin"
- displayName: Rabbitmq password
  name: PASSWORD
  required: true
  value: "secret-rabbit"