style: none
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/epam/edp-install

options:
  tag_filter_pattern: '^v'
  sort: "semVer"

  commits:
    filters:
      Type:
        - chore
        - docs
        - feat
        - fix
        - refactor
        - style
        - test

  commit_groups:
    group_by: Type
    sort_by: Custom
    title_order:
      - feat
      - fix
      - refactor
      - style
      - test
      - chore
      - docs
    title_maps:
      chore: Routine
      docs: Documentation
      feat: Features
      fix: Bug Fixes
      refactor: Code Refactoring
      style: Formatting
      test: Testing

  header:
    pattern: "^(feat|fix|docs|style|refactor|test|chore)+!?:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject

  notes:
    keywords:
      - "BREAKING CHANGE:"
