{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: v1.edp.epam.com/v1
kind: EDPComponent
metadata:
  name: docker-registry
spec:
  type: docker-registry
  url: {{ .Values.global.dockerRegistry.url }}
  visible: true
  icon: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IS0tIFVwbG9hZGVkIHRvOiBTVkcgUmVwbywgd3d3LnN2Z3JlcG8uY29tLCBHZW5lcmF0b3I6IFNWRyBSZXBvIE1peGVyIFRvb2xzIC0tPgo8c3ZnIGZpbGw9IiMwMDAwMDAiIHdpZHRoPSI4MDBweCIgaGVpZ2h0PSI4MDBweCIgdmlld0JveD0iMCAwIDMyIDMyIiBpZD0iaWNvbiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xIHsKICAgICAgICBmaWxsOiBub25lOwogICAgICB9CiAgICA8L3N0eWxlPgogIDwvZGVmcz4KICA8cGF0aCBkPSJNMTcsMTNWNkg4VjIySDI0VjEzWk0xMCw4aDV2NUgxMFptMCw3aDV2NUgxMFptMTIsNUgxN1YxNWg1WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAwKSIvPgogIDxwYXRoIGQ9Ik0yOCwxMUgxOVYyaDlaTTIxLDloNVY0SDIxWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAwKSIvPgogIDxwYXRoIGQ9Ik0yOCwyMEgyNnYyaDJ2Nkg0VjIySDZWMjBINGEyLjAwMjQsMi4wMDI0LDAsMCwwLTIsMnY2YTIuMDAyNCwyLjAwMjQsMCwwLDAsMiwySDI4YTIuMDAyNCwyLjAwMjQsMCwwLDAsMi0yVjIyQTIuMDAyNCwyLjAwMjQsMCwwLDAsMjgsMjBaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDApIi8+CiAgPGNpcmNsZSBjeD0iNyIgY3k9IjI1IiByPSIxIi8+CiAgPHJlY3QgaWQ9Il9UcmFuc3BhcmVudF9SZWN0YW5nbGVfIiBkYXRhLW5hbWU9IiZsdDtUcmFuc3BhcmVudCBSZWN0YW5nbGUmZ3Q7IiBjbGFzcz0iY2xzLTEiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIvPgo8L3N2Zz4=
{{end}}
