# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

--- # Jenkins full installation
- name: "Copy Jenkins template"
  template:
    src: "{{ item }}"
    dest: "{{ templates_dir }}/jenkins/{{ item }}"
  with_items:
    - "jenkins.yaml"

- name: "Install Jenkins app"
  shell: >
    {{ ocadm }} -n {{ project_cicd }} apply -f {{ templates_dir }}/jenkins/jenkins.yaml
  register: result
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
  no_log: true
